apiVersion: batch/v1
kind: CronJob
metadata:
  name: first-step-cronjob
spec:
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
            - image: asia-northeast1-docker.pkg.dev/planet-4f7c6/gke-argocd/first-step
              name: first-step-container
          restartPolicy: Never
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 3
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: second-step-cronjob
spec:
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
            - image: asia-northeast1-docker.pkg.dev/planet-4f7c6/gke-argocd/second-step
              name: second-step-container
          restartPolicy: Never
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 3
