apiVersion: batch/v1
kind: CronJob
metadata:
  name: second-step-cronjob
spec:
  schedule: "* * * * *"  # 毎分実行
  successfulJobsHistoryLimit: 3   # 成功したジョブの履歴を3つだけ保持
  failedJobsHistoryLimit: 1       # 失敗したジョブの履歴を1つだけ保持
  jobTemplate:
    spec:
      backoffLimit: 3 # リトライは3回まで
      template:
        spec:
          containers:
            - name: second-step-container
              image: asia-northeast1-docker.pkg.dev/planet-4f7c6/gke-argocd/second-step
          restartPolicy: Never