apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: combined-steps-cron
spec:
  #  並列実行の設定です。"Allow"と"Replace"と"Forbid"があります。
  #  "Allow"は並列実行を許可します。"Replace"は同じ名前のワークフローが実行されている場合、新しいワークフローで置き換えます。
  #  "Forbid"は同じ名前のワークフローが実行されている場合、新しいワークフローを実行しません。
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit:
  schedule: "0 0 * * *"
  workflowSpec:
    ttlStrategy:
      secondsAfterCompletion: 300 # ワークフローが完了した後に削除する時間の設定(秒)
      secondsAfterSuccess: 300 # ワークフローが成功した後に削除する時間の設定(秒)
      secondsAfterFailure: 300 # ワークフローが失敗した後に削除する時間の設定(秒)
    serviceAccountName: argocd
    # Workflowが同時に最大何個のPodを生成できるかの制限
    parallelism: 3
    entrypoint: main
    templates:
      - name: main
        steps:
          - - name: execute-first-step
              templateRef:
                name: first-step-workflow-template
                template: first-step-job
          - - name: execute-second-step
              templateRef:
                name: second-step-workflow-template
                template: second-step-job
              withSequence:
                start: "1"
                end: "10"
          - - name: execute-third-step
              templateRef:
                name: third-step-workflow-template
                template: third-step-job
            - name: execute-fourth-step
              templateRef:
                name: fourth-step-workflow-template
                template: fourth-step-job
            - name: execute-fifth-step
              templateRef:
                name: fifth-step-workflow-template
                template: fifth-step-job
