apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fifth-step-workflow-template
  labels:
    tags.datadoghq.com/env: "dev"
spec:
  entrypoint: fifth-step-job
  templates:
    - name: fifth-step-job
      serviceAccountName: argocd
      container:
        resources:
          requests:
            cpu: 750m
            memory: 64Mi
          limits:
            cpu: 1000m
            memory: 64Mi
        restartPolicy: Never
        name: fifth-step-container
        image: asia-northeast1-docker.pkg.dev/planet-4f7c6/gke-argocd/fifth-step
        command:
          - "./fifth-batch"