name: Build and Push to Artifact Registry

on:
  push:
    paths:
      - 'cmd/batch/first/**'
      - 'cmd/batch/second/**'
      - 'cmd/batch/third/**'
      - 'cmd/batch/fourth/**'
      - 'cmd/batch/fifth/**'
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.GCP_PROJECT_ID }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Determine changed directories
        id: get_changed_dir
        run: |
          git fetch
          dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^cmd/batch/(first|second|third|fourth|fifth)' | sed -E 's@^cmd/batch/([^/]*)/.*@\1@' | sort -u | tr '\n' ',')
          echo "Changed directories: $dirs"
          echo "dirs=$dirs" >> $GITHUB_ENV

      - name: Build and push using docker-compose
        if: steps.get_changed_dir.outputs.dirs != ''
        run: |
          IFS=',' read -ra DIRS <<< "${{ steps.get_changed_dir.outputs.dirs }}"
          for dir in "${DIRS[@]}"; do
            docker-compose -f docker-compose.yml build "$dir"
            docker-compose -f docker-compose.yml push "$dir"
          done
