name: Build and Push to Artifact Registry

on:
  push:
    paths:
      - 'cmd/batch/**'
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.GCP_PROJECT_ID }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Determine changed directories
        id: get_changed_dir
        run: |
          dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^cmd/batch/' | sed -E 's@(.*)/@\1@' | sort -u)
          echo "Changed directories: $dirs"
          echo "::set-output name=dirs::$dirs"

      - name: Build and push changed directories
        if: steps.get_changed_dir.outputs.dirs != ''
        uses: docker/build-push-action@v2
        with:
          context: ${{ steps.get_changed_dir.outputs.dirs }}
          file: ${{ steps.get_changed_dir.outputs.dirs }}/Dockerfile
          push: true
          tags: ${{ secrets.GCP_PROJECT_ID }}-docker.pkg.dev/gke-argocd/${{ steps.get_changed_dir.outputs.dirs }}-step:latest
